name: Deploy to Google
on: push

jobs:
  build:
    name: Install npm and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.18.0

    steps:
      - uses: actions/checkout@v2

      - name: Setting-up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verfying path
        run: ls -a

      - name: Installing dependencies
        run: |
          cd vet-patitas
          npm install
      - name: Building
        run: |
          cd vet-patitas
          npm run build\
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
        run: |
          cd vet-patitas
          npm i
          npm run build:prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
